name: smart_budget
description: "Application to track your finances."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  sqflite: ^2.4.1
  path: ^1.9.0
  get_it: ^8.0.2
  intl: any
  fl_chart: ^0.69.2
  equatable: ^2.0.7
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.2
  package_info_plus: ^8.1.1
  share_plus: ^10.1.4
  flutter_background_service: ^5.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7
  path_provider: ^2.1.5
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.4+4
  device_info_plus: ^11.2.0
  flutter_email_sender: ^6.0.3
  pdf: ^3.11.1
  printing: ^5.13.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
