name: smart_budget
description: "Application to track your finances."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  sqflite: ^2.4.1
  path: ^1.9.0
  get_it: ^8.0.2
  intl: any
  fl_chart: ^0.69.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  bloc_test: ^9.1.7

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/l10n/
